api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: portscale-net
  file:
    directory: /dynamic
    watch: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

log:
  level: INFO
